import { useContext, useRef, useState } from "react";
import { UserContext } from "./context/UserContext";

import styles from "../styles/MoviesList.module.css";

import Head from "next/head";
import MoviesList from "./components/MoviesList";
//import SearchMoviesByKeyword from "./services/SearchMoviesByKeyword";
import { useMoviesByKeyword } from "./hooks/useMoviesByKeyword";

export default function Home() {
  const { myMovies, user } = useContext(UserContext);
  const [keyword, setKeyword] = useState("");
  const foundMovies = useMoviesByKeyword(keyword);
  const inputSearchRef = useRef("");

  const handleSearch = (event) => {
    event.preventDefault();
    setKeyword(inputSearchRef.current);
    //console.log(foundMovies);
    //console.log(inputSearchRef.current)
  };

  const handleChange = (event) => {
    //setKeyword(event.target.value);
    inputSearchRef.current = event.target.value;
  };

  return (
    <div className={styles.divMovies}>
      <Head>
        <title>Moviender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Movienderingverse</h1>
      <form onSubmit={handleSearch}>
        <input
          name="searchInput"
          placeholder="write about a movie"
          onChange={handleChange}
          ref={inputSearchRef}
        ></input>
        <button>Search</button>
      </form>
      <div className={styles.movies}>
        <MoviesList myMovies={myMovies} user={user} />
      </div>
    </div>
  );
}
