import { useContext, useState } from "react";
import { UserContext } from "./context/UserContext";

import styles from "../styles/MoviesList.module.css";

import Head from "next/head";
import MoviesList from "./components/MoviesList";

import SearchForm from "./components/SearchForm";

import { useMoviesByKeyword } from "./hooks/useMoviesByKeyword";

export default function Home() {
  const { myMovies, user } = useContext(UserContext);
  const [keyword, setKeyword] = useState("");
  const foundMovies = useMoviesByKeyword(keyword);

  return (
    <div className={styles.divMovies}>
      <Head>
        <title>Moviender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Movienderingverse</h1>
      <SearchForm setKeyword={setKeyword} />
      <div className={styles.movies}>
        {keyword === "" ? (
          <MoviesList myMovies={myMovies} user={user} foundMovies={null} />
        ) : (
          <MoviesList
            myMovies={myMovies}
            user={user}
            foundMovies={foundMovies}
          />
        )}
      </div>
    </div>
  );
}
