import Head from "next/head";
import styles from "../styles/PageHome.module.css";
import MoviesList from './components/MoviesList'

export default function Home() {
  return (
    <div className={styles.div}>
      <Head>
        <title>Moviender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Movienderingverse</h1>
      <div className="movies">
        <MoviesList/>
      </div>
    </div>
  );
}
